version: '2.4'

services:
  dynamodb:
    image: cnadiminti/dynamodb-local:latest
    command: --sharedDb --inMemory
    ports:
      - 8000:8000
  admin:
      image: boogak/dynamodb-admin
      ports:
       - 8001:8001
      environment:
        - DYNAMO_ENDPOINT=http://dynamodb:8000
  serverless:
    build: .
    mem_limit: 1gb
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/app
    environment:
      # - DEBUG=*
      - AWS_REGION=localhost
      - AWS_ACCESS_KEY_ID=XXXXXXXXXXXXXXXXXXXX
      - AWS_SECRET_ACCESS_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/xxx+
    command: yarn dev
    links:
      - dynamodb
