service: clocks

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
          - "dynamodb:PutItem"
          - "dynamodb:GetItem"
          - "dynamodb:UpdateItem"
          - "dynamodb:DeleteItem"
          - "dynamodb:BatchGetItem"
          - "dynamodb:BatchWriteItem"
          - "dynamodb:Scan"
          - "dynamodb:Query"
      Resource:
          - "arn:aws:dynamodb:us-east-1:*:*"

functions:
  websocketHandler:
    handler: websocket.handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default
  streamHandler:
    handler: db-stream.handlerx
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - ConnectionsTable
              - Arn

plugins:
  - serverless-dynamodb-local
  - serverless-offline-dynamodb-streams
  - serverless-offline

resources:
  Resources:
    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: connections
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

custom:
  serverless-offline:
    allowCache: true
  dynamodb:
    stages:
      - dev
    start:
      heapInitial: 200m
      heapMax: 1g
      migrate: true
  serverless-offline-dynamodb-streams:
    endpoint: http://localhost:8000
    accessKeyId: DEFAULT_ACCESS_KEY
    secretAccessKey: DEFAULT_SECRET
